source/Icm.Sex.Web/ViewModels/ApplicationViewModel.cs
namespace Icm.Sex.Web.ViewModels
{
    using System.Collections.Generic;

    public abstract class ApplicationViewModel
    {
        protected ApplicationViewModel(string pageTitle)
        {
            MessagesForUser = new List<string>();
            PageTitle = pageTitle;
        }

        public string PageTitle { get; set; }

        public IList<string> MessagesForUser { get; set; }
    }
}

source/Icm.Sex.Web/ViewModels/HomeViewModel.cs
namespace Icm.Sex.Web.ViewModels
{
    using System.Collections.Generic;

    public class HomeViewModel : ApplicationViewModel
    {
        public HomeViewModel(string pageTitle)
            : base(pageTitle)
        {
            MessagesForUser = new List<string>();
        }

        public int ScenesCount { get; set; }

        public int BodiesCount { get; set; }
    }
}

source/Icm.Sex.Web/ViewModels/ReportViewModel.cs
namespace Icm.Sex.Web.ViewModels
{
    using Icm.Sex.Infrastructure.Reporting;

    public class ReportViewModel : ApplicationViewModel
    {
        public ReportViewModel(string pageTitle)
            : base(pageTitle)
        {
        }

        public string HtmlMarkdown { get; set; }

        public Report Data { get; set; }
    }
}

source/Icm.Sex.Web/ViewModels/SceneListViewModel.cs
namespace Icm.Sex.Web.ViewModels
{
    using System.Collections.Generic;
    using Icm.Sex.Domain.Scenes;

    public class SceneListViewModel : ApplicationViewModel
    {
        public SceneListViewModel(string pageTitle)
            : base(pageTitle)
        {
        }

        public IList<Scene> Scenes { get; set; }
    }
}

source/Icm.Sex.Web/Controllers/HomeController.cs
namespace Icm.Sex.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Icm.Sex.Domain.Bodies.Repositories;
    using Icm.Sex.Domain.Scenes.Repositories;
    using Icm.Sex.Web.ViewModels;

    public class HomeController : Controller
    {
        private readonly IBodyRepository bodyRepository;
        private readonly ISceneRepository sceneRepository;

        public HomeController(IBodyRepository bodyRepository, ISceneRepository sceneRepository)
        {
            this.bodyRepository = bodyRepository;
            this.sceneRepository = sceneRepository;
        }

        /// <summary>
        /// Default home page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(new HomeViewModel("Home")
            {
                BodiesCount = bodyRepository.Count(),
                ScenesCount = sceneRepository.Count(),
            });
        }
    }
}

source/Icm.Sex.Web/Controllers/ParseController.cs
namespace Icm.Sex.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Icm.Sex.Application.Parser;

    public class ParseController : Controller
    {
        private readonly ParsingService diaryParsingService;
        private readonly ParsingService filmParsingService;

        public ParseController(ParsingService diaryParsingService, ParsingService filmParsingService)
        {
            this.diaryParsingService = diaryParsingService;
            this.filmParsingService = filmParsingService;
        }

        /// <summary>
        /// Action for parsing a file with diary syntax.
        /// </summary>
        /// <param name="virtualFilename"></param>
        /// <returns></returns>
        public ActionResult Diary(string virtualFilename)
        {
            if (virtualFilename.Contains('/') || virtualFilename.Contains('\\'))
            {
                throw new ArgumentException("virtualFilename");
            }

            string fileName = Server.MapPath("~/bin/App_Data/" + virtualFilename);
            diaryParsingService.ParseFileName(fileName);

            return View("ParseResult", diaryParsingService.Messages);
        }

        /// <summary>
        /// Action for parsing a file with film syntax.
        /// </summary>
        /// <param name="virtualFilename"></param>
        /// <returns></returns>
        public ActionResult Film(string virtualFilename)
        {
            if (virtualFilename.Contains('/') || virtualFilename.Contains('\\'))
            {
                throw new ArgumentException("virtualFilename");
            }

            string fileName = Server.MapPath("~/bin/App_Data/" + virtualFilename);
            filmParsingService.ParseFileName(fileName);

            return View("ParseResult", filmParsingService.Messages);
        }
    }
}

source/Icm.Sex.Web/Controllers/ReportController.cs
namespace Icm.Sex.Web.Controllers
{
    using System.IO;
    using System.Web.Mvc;
    using Icm.Sex.Application.Reporting;
    using Icm.Sex.Infrastructure.Reporting;
    using Icm.Sex.Web.ViewModels;

    public class ReportController : Controller
    {
        private readonly DiaryReportService diaryReportService;
        private readonly FilmReportService filmReportService;
        private readonly IReportPrinter printer;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportController" /> class.
        /// </summary>
        /// <param name="reportingService">The reporting service.</param>
        public ReportController(DiaryReportService reportingService, FilmReportService filmReportService, IReportPrinter printer)
        {
            diaryReportService = reportingService;
            this.filmReportService = filmReportService;
            this.printer = printer;
        }

        /// <summary>
        /// </summary>
        /// <returns></returns>
        public ActionResult Diary()
        {
            return Report(diaryReportService);
        }

        /// <summary>
        /// </summary>
        /// <returns></returns>
        public ActionResult Film()
        {
            return Report(filmReportService);
        }

        private ActionResult Report(IReportService reportService)
        {
            var viewModel = new ReportViewModel(null);

            var reportData = reportService.Generate();

            viewModel.Data = reportData;

            var writer = new StringWriter();

            printer.Print(reportData, writer);

            //// var markdownSharp = new MarkdownSharp.Markdown();
            //// viewModel.HtmlMarkdown = markdownSharp.Transform(writer.ToString());
            viewModel.HtmlMarkdown = writer.ToString();
            return View("Report", viewModel);
        }
    }
}

source/Icm.Sex.Web/Controllers/SceneController.cs
using System.Web.Mvc;

namespace Icm.Sex.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using Icm.Sex.Domain.Scenes;
    using Icm.Sex.Domain.Scenes.Repositories;
    using Icm.Sex.Web.ViewModels;

    public class SceneController : Controller
    {
        private readonly ISceneRepository sceneRepository;

        public SceneController(ISceneRepository sceneRepository)
        {
            this.sceneRepository = sceneRepository;
        }

        [Route("scenes")]
        public ActionResult Index()
        {
            IList<Scene> scenes = sceneRepository.ToList();
            return View(new SceneListViewModel("Scenes") { Scenes = scenes });
        }
    }
}

source/Icm.Sex.Web/Views/Home/Index.cshtml
@using Icm.Sex.Web.ViewModels
@model HomeViewModel

<div class="jumbotron">
    <h1>Hello, world!</h1>
    <p>@Model.BodiesCount bodies in the system.</p>
    <p>@Model.ScenesCount scenes in the system.</p>
</div>

source/Icm.Sex.Web/Views/Parse/ParseResult.cshtml
@using Icm.Sex.Application.Parser
@model IEnumerable<ParseMessage>

<h2>Parse result</h2>

<ul class="parse-message-list">
    @foreach (ParseMessage message in Model)
    {
        if (message is ParseInfo)
        {
            <li class="info">@message.Message</li>
        }
        else if (message is ParseError)
        {
            var errorMessage = message as ParseError;
            <li class="error">@message.Message (@errorMessage.Exception.Message)</li>
        }
        else if (message is ParseAction)
        {
            <li class="action">@message.Message</li>
        }
        else
        {
            <li class="unknown">@message.Message</li>
        }
    }
</ul>

source/Icm.Sex.Web/Views/Report/Report.cshtml
@using Icm.Sex.Infrastructure.Reporting
@using Icm.Sex.Core
@using Chart = Icm.Sex.Infrastructure.Reporting.Chart
@model Icm.Sex.Web.ViewModels.ReportViewModel

<script>

    function weekFormatter(val) {
        if (val === 0) { return "Dom"; }
        if (val === 1) { return "Lun"; }
        if (val === 2) { return "Mar"; }
        if (val === 3) { return "Mié"; }
        if (val === 4) { return "Jue"; }
        if (val === 5) { return "Vie"; }
        if (val === 6) { return "Sáb"; }
        return val;
    }


    function monthFormatter(val) {
        if (val === 1) { return "Ene"; }
        if (val === 2) { return "Feb"; }
        if (val === 3) { return "Mar"; }
        if (val === 4) { return "Abr"; }
        if (val === 5) { return "May"; }
        if (val === 6) { return "Jun"; }
        if (val === 7) { return "Jul"; }
        if (val === 8) { return "Ago"; }
        if (val === 9) { return "Sep"; }
        if (val === 10) { return "Oct"; }
        if (val === 11) { return "Nov"; }
        if (val === 12) { return "Dic"; }
        return val;
    }

    function pieChart(guid, data) {
        $.plot('#placeholder-' + guid, data, {
            colors: ['#DB0D1B', '#1EC759', '#1E48C7', '#A236C9', '#DBA40D', '#0DD1DB'],
            series: {
                pie: {
                    show: true,
                    label: {
                        show: true,
                        radius: 3/4,
                        background: {
                            opacity: 0.5,
                            color: '#000'
                        },
                        formatter: function (label, series) {
                            return '<div style="font-size:8pt; text-align:center; padding:2px; color:white;">' + series.data[0][1] + '<br />' + Math.round(series.percent) + '%</div>';
                        }
                    }
                }
            },
            legend: {
                container: $('#legend-' + guid)
            }
        });
    }

    function stackedBarChart(guid, data, formatter) {
        $.plot('#placeholder-' + guid, data, {
            colors: ['#DB0D1B', '#1EC759', '#1E48C7', '#A236C9', '#DBA40D', '#0DD1DB'],
            series: {
                bars: {
                    show: true,
                    align: "center",
                    lineWidth: 0
                },
                stack: true
            },
            legend: {
                container: $('#legend-' + guid)
            },
            xaxis: {
                tickLength: 0,
                tickFormatter: formatter
            }
        });
    }
</script>

@helper PieChart(Icm.Sex.Infrastructure.Reporting.Chart chart)
{
    var guid = Guid.NewGuid();
    if (chart.Series.All(series => series.Points.Count() == 1))
    {
        <div class="pie-container" style="margin: 10px">
            <div id="placeholder-@guid" style="width: 300px; height: 240px;"></div>
            <div id="legend-@guid"></div>
        </div>
        <script>
            var data = [
            @foreach (var series in chart.Series)
            {
                @Html.Raw("{ color: '" + series.SeriesColor + "', label: '" + series.Label + "',  data: " + @series.Points.First().X + "},");
            }
            ];

            pieChart('@guid', data);
        </script>
    }
    else
    {
        <div class="bar-container" style="margin: 10px">
            <div id="placeholder-@guid" style="width: 600px; height: 240px;"></div>
            <div id="legend-@guid"></div>
        </div>
        <script>
            var data = [
            @foreach (var series in chart.Series)
            {
                @Html.Raw("{ color: '" + series.SeriesColor + "', label: '" + series.Label + "',  data: [" + @System.String.Join(",", series.Points.Select(point => "[" + point.X + "," + point.Y + "]")) + "] },");
            }
            ];
            @if (chart.Properties.TryGet("formatter") == "week")
            {

                <text>stackedBarChart('@guid', data, weekFormatter);</text>
            }
            else if (chart.Properties.TryGet("formatter") == "month")
            {
                <text>stackedBarChart('@guid', data, monthFormatter);</text>
            }
            else
            {
                <text>stackedBarChart('@guid', data);</text>
            }
        </script>
    }
}

@helper Header(int level, string text)
{
    if (level == 1)
    {
        <h1>@text</h1>
    }
    else if (level == 2)
    {
        <h2>@text</h2>
    }
    else if (level == 3)
    {
        <h3>@text</h3>
    }
    else if (level == 4)
    {
        <h4>@text</h4>
    }
    else if (level == 5)
    {
        <h5>@text</h5>
    }
    else if (level == 6)
    {
        <h6>@text</h6>
    }
}

@helper PrintedReport(Report report, int level)
{
    var compositeReport = report as CompositeReport;
    if (compositeReport != null)
    {
        if (compositeReport.All(subreport => subreport is Icm.Sex.Infrastructure.Reporting.Chart))
        {
            @Header(level, report.Name)
            foreach (Report subreport in compositeReport)
            {
                @PrintedReport(subreport, level + 1)
            }
        }
        else
        {
            @Header(level, report.Name)
            foreach (Report subreport in compositeReport)
            {
                <div style="clear: left"></div>
                @PrintedReport(subreport, level + 1)
            }
        }

        return;
    }

    Chart chart = report as Chart;
    if (chart != null)
    {
        <div style="float: left">
            @Header(level, chart.Name)
            @PieChart(chart)
        </div>
    }
}

@PrintedReport(Model.Data, 1)

<pre style="clear: left">
@Html.Raw(Model.HtmlMarkdown)
</pre>

source/Icm.Sex.Web/Views/Scene/Index.cshtml
@model Icm.Sex.Web.ViewModels.SceneListViewModel

<h2>title</h2>
@foreach (var scene in Model.Scenes)
{
    <h2>@scene.Description @scene.Date</h2>
}

source/Icm.Sex.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="~/Css/Site.min.css" />
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery.flot/jquery.flot.js"></script>
    <script src="~/Scripts/jquery.flot/jquery.flot.pie.js"></script>
    <script src="~/Scripts/jquery.flot/jquery.flot.stack.js"></script>
    <script src="~/Scripts/jquery.flot/jquery.flot.categories.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
</head>


<body role="document">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Diary", "Parse", new { virtualFilename = "bd.txt" })">Parse diary</a></li>
                    <li><a href="@Url.Action("Film", "Parse", new { virtualFilename = "flicks.txt" })">Parse film</a></li>
                    <li><a href="@Url.Action("Diary", "Report")">Diary report</a></li>
                    <li><a href="@Url.Action("Film", "Report")">Film report</a></li>
                    <li><a href="@Url.Action("Index", "Scene")">Manage scenes</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content" role="main">
        <div style="padding-top: 40px;">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

</body>
</html>